### ISSUE TITLE
云函数重构、封装、接口文档

### ISSUE THREAD

**Issue by favorhau** [Crop-Group/miniprogram#17]
- [x] 云函数重构
- [ ] 全局云函数二次封装(登录、添加谷物、添加记录等)
- [ ] 接口接入说明文档

**Comment by favorhau** [comment]
由于不同接口的参数列表不一，因此返回参数统一为`Promise<CloudFunctionsResult>`

```ts
type IAnyObject = Record<string, any>

interface CloudFunctionsResult {
  status: 0 | 1;
  result: IAnyObject;
  errMsg: string;
}

```

其中 result中用于储存返回参数，
不知有没有其他更好的解决方案 @situ2001

**Comment by situ2001** [comment]
> 其中 result中用于储存返回参数， 不知有没有其他更好的解决方案

目前来看，比较直白的就是先做成简单的泛型，像下面这样

```typescript
type IAnyObject = Record<string, any>

interface CloudFunctionsResult<T> {
    status: 0 | 1;
    result: T;
    errMsg: string;
}

// define type of returning object
interface User {
    id: string;
    nickname: string
}

const result: CloudFunctionsResult<User> = {
    status: 0,
    result: {
        id: '114514',
        nickname: '1919810'
    },
    errMsg: ''
}
```

**Comment by favorhau** [comment]
> > 其中 result中用于储存返回参数， 不知有没有其他更好的解决方案
> 
> 目前来看，比较直白的就是先做成简单的泛型，像下面这样
> 
> ```ts
> type IAnyObject = Record<string, any>
> 
> interface CloudFunctionsResult<T> {
>     status: 0 | 1;
>     result: T;
>     errMsg: string;
> }
> 
> // define type of returning object
> interface User {
>     id: string;
>     nickname: string
> }
> 
> const result: CloudFunctionsResult<User> = {
>     status: 0,
>     result: {
>         id: '114514',
>         nickname: '1919810'
>     },
>     errMsg: ''
> }
> ```

好的，意思就是确定请求参数和返回参数的参数类型
