### ISSUE TITLE
Will this project be updated

### ISSUE THREAD

**Issue by superasyou** [Crop-Group/miniprogram#31]
I like this project, but it doesn't look like it will be updated. Do the developers have any plans to maintain it

**Comment by favorhau** [comment]
Thanks, this project is refactoring. Because of the stress of Job hunting, I don't have plans to maintain this project. If you're interested in it, you can contact me with 1057072764@qq.com.

**Comment by favorhau** [comment]
> I like this project, but it doesn't look like it will be updated. Do the developers have any plans to maintain it

Thanks, this project is refactoring. Because of the stress of Job hunting, I don't have plans to maintain this project. If you're interested in it, you can contact me with [1057072764@qq.com](mailto:1057072764@qq.com).

**Comment by situ2001** [comment]
+1

The project is under refactoring, a refactored miniprogram written in React will be out before mid-November.
