### ISSUE TITLE
用矢量图代替现有资源文件

### ISSUE THREAD

**Issue by situ2001** [Crop-Group/miniprogram#6]
From https://github.com/Crop-Group/miniprogram/pull/5#pullrequestreview-1059987454

原项目的资源文件夹下还有不少非svg格式的图片，应该可以将大部分用svg替换之

<img width="682" alt="image" src="https://user-images.githubusercontent.com/28241963/182577556-4af60bf9-3067-4441-a476-04f50a4d2aaa.png">

- [ ] 把上述的png替换为svg

**Comment by favorhau** [comment]
资源已经已经规整，具体的样式图及路径如下:

[![vnRTsS.png](https://s1.ax1x.com/2022/08/05/vnRTsS.png)](https://imgtu.com/i/vnRTsS)
