### ISSUE TITLE
完成我的页

### ISSUE THREAD

**Issue by situ2001** [Crop-Group/miniprogram#7]
@favorhau 写下大概的思路想法

- [x] Footer
- [x] 用户昵称信息
- [x] 菜单面板
- [x] 全局登录状态逻辑

**Comment by favorhau** [comment]
- 组件化：头像信息组件、菜单栏组件，羊谷footer组件（global）
- 共享全局登陆状态，点击登录授权

**Comment by situ2001** [comment]
> * 组件化：头像信息组件、菜单栏组件，羊谷footer组件（global）
> * 共享全局登陆状态，点击登录授权

footer可以先糊出来（目前的Layout组件的设计对置底的footer不是很友好）

**Comment by favorhau** [comment]
footer已完成

**Comment by situ2001** [comment]
> footer已完成

可以做个Task list出来，参考 #2 这里的todo

- [ ] foo

**Comment by favorhau** [comment]
完成我的页 #7
（Todo已移动到顶部）

**Comment by situ2001** [comment]
oops，你忘记了做登录功能

**Comment by favorhau** [comment]
已完成全局登录函数
```javascript
const handleLogin = async () => {
     const _ = await login()
     console.log(_)
     // {
     //   status: 1,  
     //   result: {
     //     nickName: '',
     //     avatarUrl: '',
     //     ...
     // }
    //}
```
这个issue可以结束
