### ISSUE TITLE
完成我的页的跳转页（我的收藏，关于羊谷，新手引导）

### ISSUE THREAD

**Issue by favorhau** [Crop-Group/miniprogram#8]
- [ ] 我的收藏页
- [x] 关于羊谷页
- [x] 新手引导页

**Comment by favorhau** [comment]
暂时assign，还未开工

**Comment by favorhau** [comment]
- [ ] 我的收藏页

- [ ] 关于羊谷页

- [ ] 新手引导页

**Comment by situ2001** [comment]
> * [ ]  我的收藏页

这个可以先不用把状态引入，先做出基本的页面和样式
